name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install python package  
      run: |        
        pip install beautifulsoup4
        pip install requests
        pip install pandas
                
    - name: Run main.py
      run: |
        python maindata.py
        python ./city/get.py
        python NewsPage/allnews/cardnews/cardnews.py
        python NewsPage/allnews/mainnewspage/news.py
        python NewsPage/allnews/newsexplain/newsexplain.py
        python NewsPage/allnews/newpage/allnews.py
        python NewsPage/allpolicy/company/company.py